<script setup lang="ts">
import { computed, onMounted, ref, watch } from "vue";
import { useRouter } from "vue-router";
import { storeToRefs } from "pinia";
import { AlertCircle, Sparkles } from "lucide-vue-next";
import { useAppStore } from "@/stores/app";
import { useLibraryStore } from "@/stores/library";
import { useAiStore } from "@/stores/ai";
import { api } from "@/lib/api";
import type { AssetKind } from "@/lib/types";
import { assetKey } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  ToggleGroup,
  ToggleGroupItem,
} from "@/components/ui/toggle-group";

type Mode = "empty" | "ai";

const props = defineProps<{ open: boolean }>();
const emit = defineEmits<{ "update:open": [value: boolean] }>();

const store = useAppStore();
const libraryStore = useLibraryStore();
const aiStore = useAiStore();
const router = useRouter();
const { status: aiStatus, generating } = storeToRefs(aiStore);

const kind = ref<AssetKind>("skills");
const mode = ref<Mode>("empty");
const name = ref("");
const description = ref("");
const prompt = ref("");
const submitting = ref(false);

// Reset form whenever the dialog reopens — avoids leaking the previous attempt.
watch(
  () => props.open,
  (v) => {
    if (v) {
      kind.value = "skills";
      mode.value = "empty";
      name.value = "";
      description.value = "";
      prompt.value = "";
      submitting.value = false;
      // Refresh AI readiness in case the user just configured a key.
      aiStore.refreshStatus();
    }
  }
);

const trimmedName = computed(() => name.value.trim());
const trimmedPrompt = computed(() => prompt.value.trim());

const collision = computed(() => {
  if (!trimmedName.value) return false;
  const k = `${kind.value}:${trimmedName.value}`;
  return store.library.some((a) => assetKey(a) === k);
});

const nameError = computed<string | null>(() => {
  if (!trimmedName.value) return null;
  if (trimmedName.value.length > 64) return "Too long (max 64 chars)";
  if (!/^[A-Za-z0-9_-]+$/.test(trimmedName.value)) {
    return "Only letters, digits, '-' and '_'";
  }
  if (collision.value) return `A ${kind.value.slice(0, -1)} with that name already exists`;
  return null;
});

const aiReady = computed(
  () => aiStatus.value !== null && aiStatus.value.mode !== "none"
);

const canSubmit = computed(() => {
  if (!trimmedName.value || nameError.value || submitting.value || generating.value) {
    return false;
  }
  if (mode.value === "ai") {
    return aiReady.value && !!trimmedPrompt.value;
  }
  return true;
});

async function submit() {
  if (!canSubmit.value) return;
  submitting.value = true;
  try {
    if (mode.value === "ai") {
      // Generate first; only commit to disk if the AI returned something.
      // Reasoning: a half-failed flow that leaves an empty asset behind
      // forces the user to delete it before retrying with the same name.
      const generated = await aiStore.generateAsset(kind.value, trimmedPrompt.value);
      if (!generated) return;

      const created = await libraryStore.createAsset(
        kind.value,
        trimmedName.value,
        description.value.trim() || undefined
      );
      if (!created) return;

      try {
        await api.writeAsset(kind.value, trimmedName.value, generated);
      } catch {
        // The asset exists with the placeholder; we still navigate so the
        // user can paste manually. Less surprising than silently failing.
      }
    } else {
      const ok = await libraryStore.createAsset(
        kind.value,
        trimmedName.value,
        description.value.trim() || undefined
      );
      if (!ok) return;
    }

    emit("update:open", false);
    router.push({
      name: "asset-detail",
      params: { kind: kind.value, name: trimmedName.value },
    });
  } finally {
    submitting.value = false;
  }
}

function goToSettings() {
  emit("update:open", false);
  router.push({ name: "settings" });
}

onMounted(() => aiStore.refreshStatus());
</script>

<template>
  <Dialog :open="open" @update:open="emit('update:open', $event)">
    <DialogContent class="sm:max-w-md">
      <DialogHeader>
        <DialogTitle>New asset</DialogTitle>
        <DialogDescription>
          Create a skill, command or agent — empty (you fill it in) or
          generated by AI from a short prompt.
        </DialogDescription>
      </DialogHeader>

      <form class="space-y-4" @submit.prevent="submit">
        <div class="space-y-1.5">
          <Label>Kind</Label>
          <ToggleGroup
            type="single"
            :model-value="kind"
            @update:model-value="(v) => v && (kind = v as AssetKind)"
            variant="outline"
            class="w-full"
          >
            <ToggleGroupItem value="skills" class="flex-1">Skill</ToggleGroupItem>
            <ToggleGroupItem value="commands" class="flex-1">Command</ToggleGroupItem>
            <ToggleGroupItem value="agents" class="flex-1">Agent</ToggleGroupItem>
          </ToggleGroup>
        </div>

        <div class="space-y-1.5">
          <Label>Source</Label>
          <ToggleGroup
            type="single"
            :model-value="mode"
            @update:model-value="(v) => v && (mode = v as Mode)"
            variant="outline"
            class="w-full"
          >
            <ToggleGroupItem value="empty" class="flex-1">Empty</ToggleGroupItem>
            <ToggleGroupItem value="ai" class="flex-1 gap-1.5">
              <Sparkles class="size-3" />
              Generate with AI
            </ToggleGroupItem>
          </ToggleGroup>
        </div>

        <div class="space-y-1.5">
          <Label for="new-asset-name">Name</Label>
          <Input
            id="new-asset-name"
            v-model="name"
            placeholder="e.g. python-refactor"
            autofocus
            required
          />
          <p
            v-if="nameError"
            class="text-[11px] text-destructive"
          >{{ nameError }}</p>
          <p
            v-else
            class="text-[11px] text-muted-foreground"
          >Letters, digits, '-' or '_'.</p>
        </div>

        <!-- Empty mode: optional description -->
        <div v-if="mode === 'empty'" class="space-y-1.5">
          <Label for="new-asset-desc">
            Description
            <span class="text-muted-foreground">(optional)</span>
          </Label>
          <Input
            id="new-asset-desc"
            v-model="description"
            placeholder="Short summary, shown in listings"
          />
        </div>

        <!-- AI mode: prompt + status -->
        <template v-else>
          <div class="space-y-1.5">
            <Label for="new-asset-prompt">Describe what you want</Label>
            <Textarea
              id="new-asset-prompt"
              v-model="prompt"
              rows="4"
              placeholder="e.g. A skill that helps refactor Python code to follow PEP 8 — should trigger when reviewing or rewriting Python files."
            />
          </div>

          <div
            v-if="!aiReady"
            class="flex items-start gap-2.5 rounded-md border border-amber-500/40 bg-amber-500/10 p-2.5 text-[11px] text-amber-700 dark:text-amber-300"
          >
            <AlertCircle class="mt-0.5 size-3.5 shrink-0" />
            <div class="flex-1 space-y-1">
              <div>
                {{ aiStatus?.message ?? "AI backend not detected." }}
              </div>
              <button
                type="button"
                class="font-medium underline underline-offset-2"
                @click="goToSettings"
              >Open Settings</button>
            </div>
          </div>
          <p v-else class="text-[11px] text-muted-foreground">
            {{ aiStatus?.message }}
          </p>
        </template>
      </form>

      <DialogFooter>
        <Button
          variant="outline"
          :disabled="submitting || generating"
          @click="emit('update:open', false)"
        >Cancel</Button>
        <Button :disabled="!canSubmit" @click="submit">
          <Sparkles v-if="mode === 'ai'" class="size-3" />
          {{
            mode === "ai"
              ? generating || submitting ? "Generating…" : "Generate"
              : submitting ? "Creating…" : "Create"
          }}
        </Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>
</template>
